# SConscript
#
# Copyright (c) 2015 Kevin Laeufer <kevin.laeufer@rwth-aachen.de>
#
# This file is part of Ostfriesentee.
#
# Ostfriesentee is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ostfriesentee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Ostfriesentee.  If not, see <http://www.gnu.org/licenses/>.

import os

Import('env')

# build base lib
base_lib = SConscript(['../lib/base/SConscript'], exports = 'env')
base_lib_inc = os.path.join(env['OFT_BUILDPATH'], 'lib', 'base')

# build c code
c_env = env.Clone()
c_env.VariantDir(variant_dir='build/vm', src_dir='src')
c_env.Append(CPPPATH = [os.path.abspath('c')])
c_env.Append(CPPPATH = [base_lib_inc])

vm = c_env.StaticLibrary('build/vm/vm', env.Glob('build/vm/*.c'))


Return('vm')
